Add spotless plugin configuration
codehaus-plexus/plexus-pom pull request #169
Opened 2023-05-04 00:38 UTC by slachiewicz

2023-05-04 16:43 UTC, slawekjaranowski approved these changes

2023-05-05 07:55 UTC, olamy requested changes

2023-05-05 07:55 UTC, olamy commented on pom.xml
> +        <!--- newer versions of plugins requires JDK 11 -->
but there is no newer version use here?
maybe `<properties>` should have `<spotless-maven-plugin.version>2.36.0</spotless-maven-plugin.version>`

2023-05-16 10:03 UTC, gnodet commented
@slawekjaranowski @slachiewicz can you have a look at my additional commits and see if that's ok for you ?
I'd like to release the parent pom along with `plexus-utils` and `plexus-xml` 4.0.0 soon.

2023-05-16 14:14 UTC, slawekjaranowski commented on pom.xml
> +      <id>format-check</id>
IMHO additional profiles are not needed ... I simply execute ` mvn spotless:apply`

2023-05-16 16:15 UTC, merged